/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abc
 */
public class selection extends javax.swing.JFrame {

    /**
     * Creates new form selection
     */
    public selection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JRadioButton();
        btn2 = new javax.swing.JRadioButton();
        btn3 = new javax.swing.JRadioButton();
        btn4 = new javax.swing.JRadioButton();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(279, 296));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 130, 139, 45);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("School Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 274, 30);

        buttonGroup1.add(btn1);
        btn1.setFont(new java.awt.Font("Showcard Gothic", 3, 12)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 51, 51));
        btn1.setText("UPDATE");
        btn1.setOpaque(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(10, 60, 79, 23);

        buttonGroup1.add(btn2);
        btn2.setFont(new java.awt.Font("Showcard Gothic", 3, 12)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 0, 51));
        btn2.setText("UPLOAD");
        btn2.setOpaque(false);
        getContentPane().add(btn2);
        btn2.setBounds(10, 80, 81, 23);

        buttonGroup1.add(btn3);
        btn3.setFont(new java.awt.Font("Showcard Gothic", 3, 12)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 0, 102));
        btn3.setText("VIEW");
        btn3.setOpaque(false);
        getContentPane().add(btn3);
        btn3.setBounds(10, 100, 61, 23);

        buttonGroup1.add(btn4);
        btn4.setFont(new java.awt.Font("Showcard Gothic", 3, 12)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 0, 102));
        btn4.setText("DELETE");
        btn4.setOpaque(false);
        getContentPane().add(btn4);
        btn4.setBounds(10, 130, 75, 23);

        buttonGroup2.add(chk1);
        chk1.setFont(new java.awt.Font("Showcard Gothic", 2, 12)); // NOI18N
        chk1.setForeground(new java.awt.Color(51, 255, 204));
        chk1.setText("Teachers Information");
        chk1.setOpaque(false);
        getContentPane().add(chk1);
        chk1.setBounds(110, 50, 173, 23);

        buttonGroup2.add(chk2);
        chk2.setFont(new java.awt.Font("Showcard Gothic", 2, 12)); // NOI18N
        chk2.setForeground(new java.awt.Color(102, 255, 204));
        chk2.setText("Teachers Time Table");
        chk2.setOpaque(false);
        chk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk2ActionPerformed(evt);
            }
        });
        getContentPane().add(chk2);
        chk2.setBounds(110, 80, 153, 23);

        jButton2.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 200, 219, 45);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download-(2).jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 290, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        u_db_1 q= new u_db_1();
        uploadinfo s= new   uploadinfo();
        viewinfo w= new   viewinfo();
        deleteinfo t= new deleteinfo();
        updatett o= new updatett();
        uploadtt u= new uploadtt();
        viewtt p= new viewtt();
        deletett b= new deletett();

        if(chk1.isSelected()==true)
        {if (btn1.isSelected()==true)
            {q.setVisible(true);}
            else if(btn2.isSelected()==true)
            {s.setVisible(true);}
            else if(btn3.isSelected()==true)
            {w.setVisible(true);}
            else if(btn4.isSelected()==true)
            {t.setVisible(true );}
        }

        else if(chk2.isSelected()==true)
        {if (btn1.isSelected()==true)
            {o.setVisible(true);}
            else if(btn2.isSelected()==true)
            {u.setVisible(true);}
            else if(btn3.isSelected()==true)
            {p.setVisible(true);}
            else if(btn4.isSelected()==true)
            {b.setVisible(true );}
        }
this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void chk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn1;
    private javax.swing.JRadioButton btn2;
    private javax.swing.JRadioButton btn3;
    private javax.swing.JRadioButton btn4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
