
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tathagat
 */
public class timetable extends javax.swing.JFrame {

    /**
     * Creates new form timetable
     */
    public timetable() {
        initComponents();
    }
   
    
    
    
   
    String a1,a2,a3,a4,a5,a6,a7,a8;
   ArrayList  ar=new ArrayList();
    String check(String x){
         char A ;
       A=x.charAt(0);
       int p=(int) A;
          if(p>=65 & p<=122)
          {  return "a";}
            if(p<65 | p>122)
            {   return "b";}
           
        return null;
}
ArrayList create(String x,String y){  timetable tath=new timetable(); 
    
    int z=0;
     DefaultTableModel model= (DefaultTableModel) tbl.getModel();
        String day=txt2.getText();
       String day1 = day.toLowerCase();
          if( y.equals("monday"))
               z=1;
        else   if( y.equals("tuesday"))            
               z=2;
           else   if( y.equals("wednesday"))                       
               z=3;
                       else   if( y.equals("thursday"))                       
                     z=4;
                            else   if( y.equals("friday"))                
               z=5;
          else   if(y.equals("saturday"))    
                       z=6; 
      
        
 try{
            Class.forName("java.sql.Driver");
            Connection con0=DriverManager.getConnection("jdbc:mysql://localhost/teachers","root","12345");
            Statement stmt0=(Statement) con0.createStatement();
                    String query0="show tables;";
            ResultSet rs0=stmt0.executeQuery(query0);

           
           while(rs0.next())
           { String a12= rs0.getString(1);
                     
           
            Statement stmt1=(Statement) con0.createStatement();
                    String query1="select * from "+a12+";";
         ResultSet   rs1=stmt1.executeQuery(query1);
          rs1.absolute(z);     
     String a122=rs1.getString(x);
     
              if(tath.check(a122)=="b")
              {  
              ar.add(a12);
              }
                  
            stmt1.close();
      rs1.close();
         
                   
                       
                        }   
               rs0.close();
            stmt0.close();
            con0.close();

   } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Your Data Has Not Been Uploaded First Upload Your Data Or Try By Case Sensitive");
        }
   
   
    return ar;
   
}

    int random(int x){
              Random qwerty=new Random();
     int randomint=qwerty.nextInt(x);
     return randomint;
    }
       
       String check1(String x){
    String w=x.replace(" ","");
       String p=w.toLowerCase();
       return p;
    }
    String finalname(String xm,String ym){timetable tath=new timetable();
 ArrayList cv=tath.create(xm,ym);
int l=cv.size();
int no=tath.random(l);
String name=(String)cv.get(no).toString();
      return name;
 }
     ArrayList combo(String xm,String ym){timetable tath=new timetable();
 ArrayList cv=tath.create(xm,ym);
return cv;
 }
    
     
     
    
    String q,name1,name2,name3,name4,name5,name6,name7,name8;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        c2 = new javax.swing.JComboBox();
        c3 = new javax.swing.JComboBox();
        c4 = new javax.swing.JComboBox();
        c5 = new javax.swing.JComboBox();
        c6 = new javax.swing.JComboBox();
        c7 = new javax.swing.JComboBox();
        c8 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl.setBorder(new javax.swing.border.MatteBorder(null));
        tbl.setFont(new java.awt.Font("HP Simplified", 0, 14)); // NOI18N
        tbl.setForeground(new java.awt.Color(10, 10, 10));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PERIOD 1", "PERIOD 2", "PERIOD 3", "PERIOD 4", "PERIOD 5", "PERIOD 6", "PERIOD 7", "PERIOD 8"
            }
        ));
        tbl.setToolTipText("");
        tbl.setGridColor(new java.awt.Color(51, 51, 51));
        tbl.setIntercellSpacing(new java.awt.Dimension(10, 10));
        tbl.setRowHeight(100);
        tbl.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbl.setSelectionForeground(new java.awt.Color(51, 0, 51));
        tbl.getTableHeader().setResizingAllowed(false);
        tbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("ENTER NAME");

        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jButton1.setText("CREATE ARRANGEMENTS");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("DAY");

        c5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel3.setText("Period 1");

        jLabel4.setText("Period 2");

        jLabel5.setText("Period 3");

        jLabel6.setText("Period 4");

        jLabel7.setText("Period 5");

        jLabel8.setText("Period 6");

        jLabel9.setText("Period 7");

        jLabel10.setText("Period 8");

        jButton2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jButton2.setText("New Arrangement");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jButton3.setText("PRINT");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("CLOSE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton5.setText("BACK TO WELCOME");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton6.setText("BACK TO SELECTION");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel10))
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    timetable tath=new timetable();      
        int z=0;
        String day=txt2.getText();
       String day1 = day.toLowerCase();
        switch(day1){
                case "monday":     
               z=1;break;
                        case "tuesday":     
               z=2;break;
                                case "wednesday":     
               z=3;break;
                                case "thursday":     
               z=4;break;
                                        case "friday":     
               z=5;break;    case "saturday":     
               z=6;break; default :
                       JOptionPane.showMessageDialog(null,"Error");}
                       
                q=txt1.getText();
        String w=q.replace(" ","");
       String p=w.toLowerCase();
        DefaultTableModel model= (DefaultTableModel) tbl.getModel();
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/teachers","root","12345");
            Statement stmt=(Statement) con.createStatement();

            String query="select * from "+p+";";
            ResultSet rs=stmt.executeQuery(query);

            
           rs.absolute(z);
            String a=rs.getString("p1");
                String k=rs.getString("p2");
                String n=rs.getString("p3");
                String h=rs.getString("p4");
                String g=rs.getString("p5");
                String f=rs.getString("p6");
                String d=rs.getString("p7");
                String s=rs.getString("p8");

            
            rs.close();
            stmt.close();
            con.close();
         timetable uio=new timetable();
        String qw=uio.check(k);
String qa=uio.check(a);
        String qe=uio.check(n);
String qu=uio.check(h);
String qr=uio.check(g);
String qt=uio.check(f);
String qd=uio.check(d);
String qs=uio.check(s);
if(qa=="b")
{name1="";
}else if(qa=="a"){
           name1=    tath.finalname("p1",txt2.getText())+ "-"+ a;
  ArrayList bn=tath.combo("p1", txt2.getText());
int l=bn.size();
try{for(int i=0;i<=l;i++)
    c1.addItem(bn.get(i));
} catch(Exception e){

        }
}
     if(qw=="b")
{name2="";
}else if(qw=="a"){
           name2=    tath.finalname("p2",txt2.getText())+ "-" +k;ArrayList bn=tath.combo("p2", txt2.getText())  ;
int l=bn.size();
try{for(int i=0;i<=l;i++)
    c2.addItem(bn.get(i));
} catch(Exception e){

        }
  }     if(qe=="b")
{name3="";
}else if(qe=="a"){
           name3=    tath.finalname("p3",txt2.getText())+ "-"+ n;ArrayList bn=tath.combo("p3", txt2.getText());
int l=bn.size();
try{for(int i=0;i<=l;i++)
    c3.addItem(bn.get(i));
} catch(Exception e){

        }
  }   if(qu=="b")
{name4="";
}else if(qu=="a"){
           name4=    tath.finalname("p4",txt2.getText())+ "-"+ h;ArrayList bn=tath.combo("p4", txt2.getText());
int l=bn.size();
try{for(int i=0;i<=l;i++)
    c4.addItem(bn.get(i));
} catch(Exception e){

        }
  }if(qr=="b")
{name5="";
}else if(qr=="a"){
           name5=    tath.finalname("p5",txt2.getText())+"-"+   g;ArrayList bn=tath.combo("p5", txt2.getText());
int l=bn.size();
try{for(int i=0;i<=l;i++)
    c5.addItem(bn.get(i));
} catch(Exception e){

        }
  }if(qt=="b")
{name6="";
}else if(qt=="a"){
           name6=    tath.finalname("p6",txt2.getText())+ "-" + f;ArrayList bn=tath.combo("p6", txt2.getText());
int l=bn.size();
try{for(int i=0;i<=l;i++)
    c6.addItem(bn.get(i));
} catch(Exception e){

        }
  }if(qd=="b")
{name7="";
}else if(qd=="a"){
           name7=    tath.finalname("p7",txt2.getText())+ "-" +  d;ArrayList bn=tath.combo("p7", txt2.getText());
int l=bn.size();
try{for(int i=0;i<=l;i++)
    c7.addItem(bn.get(i));
} catch(Exception e){

        }
  }if(qs=="b")
{name8="";
}else if(qs=="a"){
           name8=    tath.finalname("p8",txt2.getText())+  "-" + s;ArrayList bn=tath.combo("p8", txt2.getText());
int l=bn.size();
try{for(int i=0;i<=l;i++)
    c8.addItem(bn.get(i));
} catch(Exception e){

        }
  }
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Your Data Has Not Been Uploaded First Upload Your Data Or Try By Case Sensitive");
        }
           model.addRow(new Object []{q,name1,name2,name3,name4,name5,name6,name7,name8});
  
       tbl.setGridColor(Color.BLACK);
       tbl.setShowVerticalLines(true);
       tbl.setShowHorizontalLines(true);
       jButton1.setEnabled(false);
       jButton3.setEnabled(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        c1.removeAllItems();
                c2.removeAllItems();
        c3.removeAllItems();
        c4.removeAllItems();
        c5.removeAllItems();
        c6.removeAllItems();
        c7.removeAllItems();
        c8.removeAllItems();
jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{boolean c=tbl.print();
        if(c)
                      JOptionPane.showMessageDialog(null,"Arrangements Printed");
        else {
                        JOptionPane.showMessageDialog(null,"Printing Failed");
        }
  
        
        } catch(PrinterException pe){
            JOptionPane.showMessageDialog(null,"Your Printer Is Not Connected");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         Welcome p=new Welcome();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          selection p=new selection();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JComboBox c3;
    private javax.swing.JComboBox c4;
    private javax.swing.JComboBox c5;
    private javax.swing.JComboBox c6;
    private javax.swing.JComboBox c7;
    private javax.swing.JComboBox c8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
