import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abc
 */
public class uploadinfo extends javax.swing.JFrame {

    /**
     * Creates new form uploadinfo
     */
    public uploadinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        rbtn1 = new javax.swing.JRadioButton();
        rbtn2 = new javax.swing.JRadioButton();
        rbtn3 = new javax.swing.JRadioButton();
        txt2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 340));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Subject");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(36, 137, 53, 17);

        buttonGroup1.add(rbtn1);
        rbtn1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        rbtn1.setText("TGT");
        rbtn1.setOpaque(false);
        getContentPane().add(rbtn1);
        rbtn1.setBounds(40, 170, 51, 25);

        buttonGroup1.add(rbtn2);
        rbtn2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        rbtn2.setText("PGT");
        rbtn2.setOpaque(false);
        getContentPane().add(rbtn2);
        rbtn2.setBounds(40, 200, 51, 25);

        buttonGroup1.add(rbtn3);
        rbtn3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        rbtn3.setText("Other");
        rbtn3.setOpaque(false);
        getContentPane().add(rbtn3);
        rbtn3.setBounds(40, 230, 61, 25);
        getContentPane().add(txt2);
        txt2.setBounds(155, 137, 226, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("Upload Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(192, 200, 117, 25);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setText("School Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 413, 45);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(36, 97, 40, 17);
        getContentPane().add(txt1);
        txt1.setBounds(155, 87, 226, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("Back to main page");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(155, 236, 199, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images-(3).jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, -6, 410, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String  i = null;
        if(rbtn1.isSelected()==true)
        i="TGT";
        else if((rbtn2.isSelected()==true))
        i="PGT";
        else if(rbtn3.isSelected()==true)
        i="Other";
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/teachers1","root","12345");
            Statement stmt=(Statement) con.createStatement();

            String query="insert into tat values('"+txt1.getText()+"','"+txt2.getText()+"','"+i+"');";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Record Successfully Uloaded");

            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        selection q=new selection();
        q.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbtn1;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JRadioButton rbtn3;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
