import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abc
 */
public class uploadtt extends javax.swing.JFrame {

    /**
     * Creates new form uploadtt
     */
    public uploadtt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt0 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(692, 250));
        getContentPane().setLayout(null);

        jLabel9.setText("Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(39, 195, 27, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Monday"},
                {"Tuesday"},
                {"Wednesday"},
                {"Thursday"},
                {"Friday"},
                {"Saturday"}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(0, 45, 63, 131);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setText("School Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(83, 0, 413, 45);
        getContentPane().add(txt0);
        txt0.setBounds(84, 182, 131, 30);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Period 1", "Period 2", "Period 3", "Period 4", "period 5", "period 6", "Period 7", "Period 8"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl.setOpaque(false);
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(69, 45, 610, 131);

        jButton1.setFont(new java.awt.Font("Wide Latin", 3, 18)); // NOI18N
        jButton1.setText("Upload Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(233, 187, 231, 27);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("Back to main page");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 187, 199, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images-(4).jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 690, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String lk=txt0.getText();
        String hg=lk.replace(" ","_");
       String yu=hg.toLowerCase();
        DefaultTableModel model= (DefaultTableModel) tbl.getModel();

        try {
            Class.forName("java.sql.Driver");

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/teachers","root","12345");
            Statement stmt=(Statement) con.createStatement();

            String v=yu;
            String query="create table "+v+"(p1 varchar(10),p2 varchar(10),p3 varchar(10), p4 varchar(10),p5 varchar(10),p6 varchar(10),p7 varchar(10),p8 varchar(10));";

            stmt.executeUpdate(query);

            con.close();

        }

        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Errors");
        }

        try {
            Class.forName("java.sql.Driver");

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/teachers","root","12345");

            Statement stmt1=(Statement) con.createStatement();
            Statement stmt2=(Statement) con.createStatement();
            Statement stmt3=(Statement) con.createStatement();
            Statement stmt4=(Statement) con.createStatement();
            Statement stmt5=(Statement) con.createStatement();
            Statement stmt6=(Statement) con.createStatement();
            Statement stmt7=(Statement) con.createStatement();
            String v=yu;

            String q;
            q = (String) model.getValueAt(0, 0);
            String w;
            w = (String) model.getValueAt(0, 1);
            String e;
            e= (String) model.getValueAt(0, 2);
            String r;
            r = (String) model.getValueAt(0, 3);
            String t;
            t = (String) model.getValueAt(0, 4);
            String y;
            y = (String) model.getValueAt(0, 5);
            String u;
            u = (String) model.getValueAt(0, 6);
            String i;
            i = (String) model.getValueAt(0, 7);
            String pl;
            pl = (String) model.getValueAt(1, 0);
            String m;
            m = (String) model.getValueAt(1, 1);
            String z;
            z = (String) model.getValueAt(1, 2);
            String x;
            x = (String) model.getValueAt(1, 3);
            String caa;
            caa = (String) model.getValueAt(1, 4);
            String l;
            l = (String) model.getValueAt(1, 5);
            String b;
            b = (String) model.getValueAt(1, 6);
            String qa;
            qa = (String) model.getValueAt(1, 7);
            String ba;
            ba = (String) model.getValueAt(2, 0);
            String bs;
            bs = (String) model.getValueAt(2, 1);
            String bd;
            bd = (String) model.getValueAt(2, 2);
            String bf;
            bf = (String) model.getValueAt(2, 3);
            String bg;
            bg = (String) model.getValueAt(2, 4);
            String bh;
            bh = (String) model.getValueAt(2, 5);
            String bj;
            bj = (String) model.getValueAt(2, 6);
            String bk;
            bk = (String) model.getValueAt(2, 7);
            String bl;
            bl = (String) model.getValueAt(3, 0);
            String bz;
            bz = (String) model.getValueAt(3, 1);
            String bx;
            bx = (String) model.getValueAt(3, 2);
            String bc;
            bc = (String) model.getValueAt(3, 3);
            String bv;
            bv = (String) model.getValueAt(3, 4);
            String bb;
            bb = (String) model.getValueAt(3, 5);
            String bn;
            bn = (String) model.getValueAt(3, 6);
            String bm;
            bm = (String) model.getValueAt(3, 7);
            String bas;
            bas = (String) model.getValueAt(4, 0);
            String bad;
            bad = (String) model.getValueAt(4, 1);
            String baf;
            baf = (String) model.getValueAt(4, 2);
            String bag;
            bag = (String) model.getValueAt(4, 3);
            String bah;
            bah = (String) model.getValueAt(4, 4);
            String baj;
            baj = (String) model.getValueAt(4, 5);
            String bak;
            bak = (String) model.getValueAt(4, 6);
            String bal;
            bal = (String) model.getValueAt(4, 7);
            String baz;
            baz = (String) model.getValueAt(5, 0);
            String bax;
            bax = (String) model.getValueAt(5, 1);
            String bac;
            bac = (String) model.getValueAt(5, 2);
            String bav;
            bav = (String) model.getValueAt(5, 3);
            String bqq;
            bqq = (String) model.getValueAt(5, 4);
            String bww;
            bww = (String) model.getValueAt(5, 5);
            String bee;
            bee = (String) model.getValueAt(5, 6);
            String brr;
            brr = (String) model.getValueAt(5, 7);

            String query1="insert into "+v+" values('"+q+"','"+w+"','"+e+"','"+r+"','"+t+"','"+y+"','"+u+"','"+i+"');";
            String query2="insert into "+v+" values('"+pl+"','"+m+"','"+z+"','"+x+"','"+caa+"','"+l+"','"+b+"','"+qa+"');";
            String query3="insert into "+v+" values('"+ba+"','"+bs+"','"+bd+"','"+bf+"','"+bg+"','"+bh+"','"+bj+"','"+bk+"');";
            String query4="insert into "+v+" values('"+bl+"','"+bz+"','"+bx+"','"+bc+"','"+bv+"','"+bb+"','"+bn+"','"+bm+"');";
            String query5="insert into "+v+" values('"+bas+"','"+bad+"','"+baf+"','"+bag+"','"+bah+"','"+baj+"','"+bak+"','"+bal+"');";
            String query6="insert into "+v+" values('"+baz+"','"+bax+"','"+bac+"','"+bav+"','"+bqq+"','"+bww+"','"+bee+"','"+brr+"');";

            stmt1.executeUpdate(query1);
            stmt2.executeUpdate(query2);
            stmt3.executeUpdate(query3);
            stmt4.executeUpdate(query4);
            stmt5.executeUpdate(query5);
            stmt6.executeUpdate(query6);
            JOptionPane.showMessageDialog(null,"Successfully Uploaded");
            con.close();

        }

        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        selection q=new selection();
        q.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt0;
    // End of variables declaration//GEN-END:variables
}
