import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abc
 */
public class viewtt extends javax.swing.JFrame {

    /**
     * Creates new form viewtt
     */
    public viewtt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(470, 300));
        getContentPane().setLayout(null);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Period 1", "Period 2", "Period 3", "Period 4", "period 5", "period 6", "Period 7", "Period 8"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl.setEditingColumn(0);
        tbl.setEditingRow(0);
        tbl.setEnabled(false);
        tbl.setFillsViewportHeight(true);
        tbl.setRowSelectionAllowed(false);
        tbl.setUpdateSelectionOnSort(false);
        tbl.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(79, 51, 375, 131);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Monday"},
                {"Tuesday"},
                {"Wednesday"},
                {"Thursday"},
                {"Friday"},
                {"Saturday"}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 51, 63, 131);
        getContentPane().add(txt1);
        txt1.setBounds(143, 195, 98, 30);

        jButton1.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        jButton1.setText("View Time Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 238, 245, 23);

        jLabel2.setText("Enter Your Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(251, 211, 81, 14);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setText("School Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 413, 45);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("Back to main page");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(255, 231, 199, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(41, 200, 67, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download-(1).jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 470, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String q=txt1.getText();
        String w=q.replace(" ","_");
       String p=w.toLowerCase();
        DefaultTableModel model= (DefaultTableModel) tbl.getModel();
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/teachers","root","12345");
            Statement stmt=(Statement) con.createStatement();

            String query="select * from "+p+";";
            ResultSet rs=stmt.executeQuery(query);

            while(rs.next()){
                String a=rs.getString("p1");

                String k=rs.getString("p2");
                String j=rs.getString("p3");
                String h=rs.getString("p4");
                String g=rs.getString("p5");
                String f=rs.getString("p6");
                String d=rs.getString("p7");
                String s=rs.getString("p8");

                model.addRow(new Object []{a,k,j,h,g,f,d,s});
            }
            rs.close();
            stmt.close();
            con.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Your Data Has Not Been Uploaded First Upload Your Data Or Try By Case Sensitive");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        selection q=new selection();
        q.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                DefaultTableModel model= (DefaultTableModel) tbl.getModel();
int rows = model.getRowCount();
if (rows>0)
    for (int i=0; i<rows;i++){model.removeRow(0);}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
